### ISSUE TITLE
EPIC: implement serverStatus API

### ISSUE THREAD

**Issue by a-saksena** [hashgraph/hedera-block-node#154] opened 2024-08-29 17:00 UTC
Refer https://github.com/hashgraph/hedera-protobufs/blob/d5e69887fc65796c6afdcc140b5140d4133bb5f4/block/block_service.proto#L802 for spec

**Comment by Nana-EC** [comment] 2024-10-09 14:47
Dupe of #147 .
Closing and moving content above over

**Closed by Nana-EC** 2024-10-09 14:47 UTC
Labels: Epic
